### ISSUE TITLE
bossbar bug

### ISSUE THREAD

**Issue by jhh8** [ReactiveDrop/reactivedrop_public_src#13]
the first boss bar in the array of boss bars (one which has lowest column or row) breaks when the map is loaded for the first time https://imgur.com/a/mCJdL0R , next time map is loaded it seems to be fine https://imgur.com/a/snpXGSB . however on illyn forest i noticed it breaks sometimes on next map loads too, breaks also with addons disabled

**Comment by Nyubs** [comment]
illyn forest generator healthbar should be removed imo. the generator has lights that indicate the status.
and the giant bar kinda ruins the immersion cause its just to big and obnoxious.

if a healthbar is needed: a little bar like doors or the special shield have in lana sewer, would be a better choice instead of a giant HUD indicator blocking the screen for so long.
this would also get rid of the wrong hudbug on that map.
