### ISSUE TITLE
[feature]According to the length of the text, the time for displaying subtitles is automatically calculated

### ISSUE THREAD

**Issue by zhongqingsong** [ReactiveDrop/reactivedrop_public_src#154]
In the current maps, the speech is very long and there is a lot of text. However, the text may only be shown for a second or two, with no plot instructions at all. (The project is too big, and local compilation is more troublesome. Therefore, I can only give one opinion.)
To solve this problem, I have an idea. For example, we define a rule: how many characters are displayed for a few seconds, and have the shortest time.
For example, we stipulate that:
1. The subtitle display time should be at least 1 second.
2. Display 1 second for every 15 characters, and make up 1 second for less than 1 second. Depending on the language, this character count standard can be added to a configuration table, which can be adjusted dynamically.
In this case, for example, there is an English, and the length of the string is 50. Then he needs to show 4 seconds. If you feel long, or short, adjust the character standard to 20. In this way, it will display 3 seconds. Similarly, this English translation is in other languages, such as 30 characters in a certain language, and at the same time its character standard is 10. Then he showed 3 seconds.
Through this dynamic approach, you can fully liberate the personnel to manually configure the voice and text of the personnel to greatly improve the efficiency.

**Comment by BenLubar** [comment]
Related: #134 

Right now there are two ways we handle subtitles for story dialogue:
- VCD/FacePoser cutscenes (used in Nam Humanum and any maps that haven't been recompiled since the introduction of `asw_voiceover_dialogue`) - subtitle length is set by the author of the scene, often accidentally set to 1 second. If there are specific lines of dialogue this happens for, it'd be helpful in tracking down what needs to be fixed.
- `asw_voiceover_dialogue` (new) - uses the length of the audio file on the server side to determine how long the caption shows.

We could add an override on the client (where the language of the subtitle is actually known) to adjust subtitle duration as the closed caption user messages come in as described above.

**Comment by zhongqingsong** [comment]
And this one, At this point, I can try to press F1 or something and select the robot.
First, the subtitles are displayed super fast, and they are displayed in an instant. Second, in many cases, the voice is still playing, but the text has been displayed.
Because this is a beta version, according to your description above, you have adapted the subtitles of all maps, except for the Nam map. However, in the beta version, it doesn't play as you say.
So, let me mention it separately: if you are repairing or have already repaired, please ignore my feedback; if it is repaired, the effect may not be particularly ideal.

**Comment by BenLubar** [comment]
Reproduced. Looks like my code to generate closed caption hashes isn't working correctly on listen servers.
