### ISSUE TITLE
TEST UPDATES BEFORE RELEASING

### ISSUE THREAD

**Issue by Nyubs** [ReactiveDrop/reactivedrop_public_src#34]
it gets ridicilous.
the whole year random useless miniupdates instead of announced once like monthly.

get some professional spirit and put quality out. hotfixes edit the updatepost.

quantity doesnt matter if the quality is a mess.

also workshop is still not fixed, just a workaround that is inferior was added.

and maybe start some inside communication. if you really wanne kill the popularity continue that and gamebanning people cause chinese.

**Comment by Nyubs** [comment]
WORKSHOP doesnt work since you crashed all servers for 1 hour 200 times.

forcing download is not the same as the normal check seeing if update needed.

this is not a fix. this is just an workaround you made.

WORKSHOP STILL BUGGED. and all your doing.




and useless constant updates without content and broken things that need more updates makes people leave the game.
not everyone is spoiled and has a fast pc or unlimited bandwight or the patience to constantly have servers to update or your game or restart game cause friends cannot join.


learn to be professional once.  announce updates
for once test something. beta content always broken and sitll gets pushed.
so often not even put in beta last months.


quantity like that is just a sad statement.
put quality out, learn to test.
if you would learn to test once something for real, you would do constant good work.
BUT nearly everything you pushed yourself broke something. and could be evaded with 1 brain using tester.

**Comment by BenLubar** [comment]
There were no changes to the dedicated server Workshop integration other than the ability to download collections between the addition of `rd_workshop_use_reactivedrop_folder` in March and the recent addition of `rd_workshop_unconditional_download_item`.

All of the recent updates have been designed to update the server and client separately, so that bugfixes could be applied to each side independently without breaking matchmaking.

If people don't have enough bandwidth to download an optional &lt;100 kilobyte update, they definitely don't have enough bandwidth to play a Source Engine game online. Opening the front page of any major news website will download more data to your computer than the recent incremental updates.

Updates go out regularly (in many cases daily) to the beta branch, but critical updates like crash fixes are pushed directly to the live branch after local testing.
