### ISSUE TITLE
[bug]accident32 map6 door animation issue

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#347]
wrong wielding position. note the door opens to the right direction

https://user-images.githubusercontent.com/11514506/194742039-e4b55d63-3ad6-4310-836e-b49f8bbe7d9b.mp4

**Comment by BenLubar** [comment]
Aren't doors always welded from that side?

**Comment by ywgATustcbbs** [comment]
> Aren't doors always welded from that side?

i think it should be welded from the "moving" free edge, not the edge mounted into the wall.


https://user-images.githubusercontent.com/11514506/194767357-ee5aa833-5c51-4b8c-827f-660ecf2a0671.mp4

**Comment by BenLubar** [comment]
Weird

@jhh8 is that a custom model? I don't think the weldable side of the door is something that can be changed in hammer.

**Comment by jhh8** [comment]
Should be able to be changed, might depend either on door's rotation or the left/right model or the left/right keyvalue, this is not a big issue since to me it makes sense that door can be welded from any side to prevent it from sliding so gonna fix this as bonus fix when updating the map for other reasons
