### ISSUE TITLE
[question]l4d legacy code

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#426]
in file \src\game\client\swarm\gameui\swarm\vgamesettings.cpp
line 725-890
it seems that asrd is using l4d*** game settings strings?

btw, line 891 and below seem to be flyout menu items that support 12-16 players, and i also find the menu texts in language files. but it dosen't show up in game. Editing config file rd_last_game_maxplayers "12" won't work either. currently i guess the line:
            m_drpNumSlots = dynamic_cast< DropDownMenu* >( FindChildByName( "DrpNumSlots" ) );
is the key to this. But I can't find any clues about "DrpNumSlots"

**Comment by BenLubar** [comment]
The translation keys have been like that since Valve released Alien Swarm in 2010. They didn't see any reason to change them after forking from Left 4 Dead, and honestly I don't see a reason either. They work, and the names of those strings having L4D in them isn't hurting anything.

The support for 12-16 players is for future expansion. The flyout menu doesn't have entries for those player counts, but the code is written, so a workshop addon could potentially add those options.

**Comment by ywgATustcbbs** [comment]
> The support for 12-16 players is for future expansion. The flyout menu doesn't have entries for those player counts, but the code is written, so a workshop addon could potentially add those options.

Dose this mean the entries are stored like key-value pairs or something in an external vpk file? The root name is "DrpNumSlots". And two entries named like rd_player_4_slots And 8_slots are listed as it's children, i guess? Then i can create a mod which inerts two more entries under that root will do the work. Am i right?

**Comment by BenLubar** [comment]
Yes, the file that controls this is `resource/ui/basemodui/dropdownnumslots.res` in `pak01_dir.vpk`.

**Comment by ywgATustcbbs** [comment]
Thanks. Finally managed to unlock 12/16 players.
