### ISSUE TITLE
[bug]unexpected blocking in NH map3

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#428]
It seemed that something was blocking marine near the pipe leaks.

https://user-images.githubusercontent.com/11514506/205904659-b25b27fa-71da-42a8-a110-1da9b27369a0.mp4

**Comment by BenLubar** [comment]
Weird, I don't see anything in that spot in the level editor.

**Comment by ywgATustcbbs** [comment]
Tested it several times, it would disappear after several fast restart. Possibly caused by spawnner? Or caused by lerp too low that makes small fluttering of game ticks observable?

**Comment by jhh8** [comment]
i guess a stutter when a vis cluster renders, can see by the net graph that updaterate suddently drops

**Comment by BenLubar** [comment]
![image](https://user-images.githubusercontent.com/4257305/206093344-2c06d124-6b42-424f-aac7-c668d5a2eaaa.png)
This is hard to demonstrate in-game because most of the props have fade distances set, but when you pass the yellow line, the stuff in the red circle enters the PVS. Looks like mostly eggs and biomass, with a few drones and explosive barrels.

There's also stuff coming into the PVS past the top and bottom of this screenshot, including a projected texture to the west (down).

Options to deal with this include moving stuff so it's not all entering the PVS at once, adding a viscluster so some of this stuff is in the PVS when you first spawn into the level, or moving enemy spawns so you're less likely to be in combat when the networking hitch happens.

**Comment by jhh8** [comment]
![image](https://user-images.githubusercontent.com/95616101/206159744-ee08d7a1-bc74-4051-a7c7-bcac47d1d80f.png)
could also try splitting this area into two parts

**Comment by geotavros** [comment]
The issue demonstrated in video is network choke due to PVS as Ben said. However PVS itself is not the cause. Biomass and eggs generate and insane amount of network traffic. Thus when several biomass and eggs appear in PVS at once there's a big chunk of networking data coming through channel and chokes in it if `rate `is not enough.
This was happening on Syntek Residential since 2010 with default client settings(rate, updaterate).

The proper fix is to prevent biomass and eggs sending so much data every frame. Especially biomass. It is a static entity that doesn't even need to send anything at all since it doesn't move. I assume it is sending its morphing animation(flexes) every frame.

**Comment by ywgATustcbbs** [comment]
The game in video was hosted on my own pc. i don't think network is a problem when dealing with loopback ip. And my gear is r7 3900x + 32g + 2070s + 1t sad. So pc is not bottleneck. If the issue is caused by entity data transmission, why it disappeared after sever restart. Aren't the data always transmitted each time? Biomass might not be the problem. It behaved as if something needs post-loading.

**Comment by BenLubar** [comment]
> could also try splitting this area into two parts

That could work but only if we also split an earlier area (PVS is calculated per leaf, not per coordinate).

> I assume it is sending its morphing animation(flexes) every frame.

That would also be my guess for biomass and eggs. Will have to experiment with how to enable client-side animation on them without breaking state changes for eggs.

> i don't think network is a problem when dealing with loopback ip.

There's a limit to how much data the game is *willing* to send, and usually that's much less than the amount it *can* send if it were to fully saturate the connection, especially for loopback.

**Comment by ywgATustcbbs** [comment]
> That would also be my guess for biomass and eggs. Will have to experiment with how to enable client-side animation on them without breaking state changes for eggs.

What confused me is that the issue only appear for the first several restarts when this map is re-loaded. It won't hpaaen again until another re-load. If it's caused by biomass or something, It should happen all the time.

**Comment by jhh8** [comment]
> That could work but only if we also split an earlier area (PVS is calculated per leaf, not per coordinate).

hm then i guess into two parts the section itself and the one before it, so the heavy load section gets split into two parts and loads half and then another half after 2-3 seconds of running

**Comment by jhh8** [comment]
also it seems like to me that the cbaseflex class sends a 96-element float array

**Comment by BenLubar** [comment]
`dtwatchclass DT_BaseFlex` -> nothing is being sent (the 96 element float array is explicitly excluded)
`dtwatchclass DT_ASW_Alien_Goo` -> a few things are being sent, but not an amount that should cause a hitch
