### ISSUE TITLE
[question] A small map prop issue in acc32 map 1

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#466]
The camera is rotating when naded while others don't. Might be fixed to reduce the load of physics engine. Anyway it won't be a problem for modern PCs.

https://user-images.githubusercontent.com/11514506/212544621-3fcccc35-ecd5-46f1-b93a-402991e1cad4.mp4

**Comment by jhh8** [comment]
i feel like its a funny thing but its kind of weird so did it only to one camera

**Comment by ywgATustcbbs** [comment]
> i feel like its a funny thing but its kind of weird so did it only to one camera

It's really not a problem. i only checked this one and several others nearby, only this one has the rotating ability. It could increase the engine work load by a tiny amount. But Considering steam deck and some similar low performance machines, It might be useful to fix it.

**Comment by ax-now** [comment]
Its not a bug, the graphics engine makes the props move when they get an explosion or something.
If you are afraid of losing fps because of that don't worry, it does not affect the fps, well surely a little but much less than a simple drone unit that moves on the map.
And it dosent affect gameplay + its funny so why would you like to fix it? :P
