### ISSUE TITLE
Overwatch player system

### ISSUE THREAD

**Issue by mithrand0** [ReactiveDrop/reactivedrop_public_src#475]
There are users, who violate the online rules of the game. These rules can be anything from toxic behavior, excessively kick players, harassment and cheating. 

The current Steam system can report players, but it's not intuitive to use. It would be nice, to deploy an easier to use community reporting system similar to what cs:go is using. This way, we can use the community to report bad behavior, and new cheats, bundled with proof.

What would be nice:

- an easy way to report a user in-game, i.e. click on the users name > report
- a clear screen the user agrees with some terms;
- a description, together screenshot or demo recording of the violation;
- steamid or reporter and reported user;
- a way to add it even if you are kicked.

In general, bad people will get reported by multiple players, the system would sort of prioritize itself.

We can use the existing backend system we already utilize that aggregates proof of cheaters, steam reports and other stuff. It has built-in translation for the reports and info from servers already.

The main challenge will probably be the in-game ui.

_**Update: everything is sort of finished, except the in-game gui.**_

**Comment by jhh8** [comment]
what would be the punishment?

**Comment by mithrand0** [comment]
Users that violate the TOS get sanctioned according to Steam Policy.

**Comment by ywgATustcbbs** [comment]
A user behavior rating system similar to dota2 will be appreciated. My suggestion is to force display user ratings to every player in lobby. 

The rating could be based on up vote or down vote from the team (great game experience or bad experience, But not cheating or Such listed above), together with reporting(as listed). 

To avoid abusing rating/reporting system, a user will have  limited number of tickets within a period, for example 2tickets/week or 4/m. Tickets can also be given on play time, 1 ticket per 5 game time. Dota2 seems to take a hybrid ticket strategy. Reporting ticket should be unlimited.

When It come to punishment, different levels should be given to a user:
1. For a user with low rating But never be reported violating community behavior rules, displaing his rating is the punishment.
2. For the confirmed reportings, punishments could be several hours of banning to permanent banning based on reported times.

The current promotion system is almost useless. Why not combine The promotion and rating/reporting system? Each confirmed report will decrease the promotion level by 1 for some time.  Each promotion level will increase the the reward of hoiaf by a small percent(1.5% per extera promotion, 9% for 7promotions). This will further increase the penalty of cheating in ranked servers. Because reporting will decrease the reward. And This will also bring promotion system back to live.

For Ui design, We could use promotion medal texts to show the player reputation. It is reasonable to show a marines promotions along with some important career records.

**Comment by mithrand0** [comment]
Above is nice, but I propose to keep it as simple as possible at start. We don't have a large community, and we don't have hundreds of hours of development time to spare to code such system.

**Comment by BenLubar** [comment]
On the Dota 2 thing: the experimental psychologist who works for Valve did a presentation on how it worked: https://youtu.be/K0GZMA6c0T4?t=2001

**Comment by mithrand0** [comment]
About the reporting / overwatch system, we have split this task into few parts:

- [X] Implement new api reporting endpoint
- [X] Implement parsing and logic in web backend
- [X] Implement api calls in game
- [X] Design a GUI in the game for it.

First three are finished. With the last task, we could use some help to speed things up.

**Comment by mithrand0** [comment]
This feature is implemented.
