### ISSUE TITLE
Redesign mission selection screen

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#5]
The new mission selection screen will have missions laid out in a grid with details on the right. The Deathmatch and Bonus Missions campaigns will be removed and replaced with tabs in this new UI.

Mission overview files and campaign files can now include `tag` keys, of which `bonus` and `deathmatch` are used for missions and no tags are currently used for campaigns. Tags are unordered and case-insensitive.

- [x] Update workshop uploader to understand tagged mission overviews.
- [x] Clean up mission chooser frame and merge with lobby creation mission chooser.
- [x] ~~Implement map-based starting mission selection for campaigns (add advanced setting to change this to a simple grid).~~ (decided against this in prototyping)
- [x] Ensure new UI works well with controller.
- [x] Ensure new UI scales well to various resolutions.
- [ ] Update Steam Workshop guide.

**Feedback:**
- [x] Make the tabs look better.
- [x] Clicking on the starting mission name after selecting a campaign mission should go back to the campaign.
- [x] Reduce size of `ReactiveDropChallenges` stringtable payloads to avoid "overflow error writing stringtable baseline" crash.
- [x] Non-campaign missions have missing rich presence logic.
- [x] Non-campaign missions don't keep marine selections on retry.
- [ ] Add an indicator for official campaigns/missions.
- [ ] Indicate number of missions in campaign.

**Legacy Addons:**
Rationale: Addons that have not been updated should still go to the correct part of the mission chooser.
These tags will be hidden on the workshop, but visible in the uploader. Mappers are free to remove (or keep) the tag when publishing an update.
- [x] Add `adminoverride_Bonus` tag to addons that have one-mission campaigns that are not explicitly presented as campaigns ingame. `adminoverride_Bonus` will cause the campaign to disappear and the mission to be tagged as bonus and inherit the hidden campaign's credits filename.
- [x] Add `adminoverride_Deathmatch` tag to addons that have one-mission campaigns containing a deathmatch mission with a filename starting with `dm_`. `adminoverride_Deathmatch` will cause the campaign to disappear and the mission to be tagged as deathmatch and inherit the hidden campaign's credits filename.
- [x] Implement stats website handling for these tags.
- [x] Implement client handling for these tags.
- [x] Implement listen server handling for these tags.
- [x] Implement dedicated server handling for these tags.
- [x] **When ready for release:** Remove "Campaign" tag and add "Bonus" tag to relevant addons.

**Comment by Nyubs** [comment]
wow good work coming again.

suggestions:

campgain descriptionarea should have a half transparent background atleast, cause some backgrounds (specially custom once) can make it hard to read the text probally.

a scrollbar should be added on the campgain selection, cause not everyone has his mousewheel functions being able to scroll.

ideas:
maybe add a subtap for installed map to make the selection faster, or a favourite option that can be customized that compares your maps with the avaible server once, and doesnt show the not subbed once.

maybe add an "official map" text to the official maps, and a mapcount while hovering over the campgain.

maybe add the ability for keyboard mouse users to doubleclick (like windows OS mostly works on desktop) to select a campgain and open it, instead of simple click and to reduce wrong votes on accidental simple clicks.
if that makes problems with controllers, this can be dismissed, its just a personal preference and i can see that doubleclicking with controller would be annoying.

didnt test maybe its working already, being able to to use WASD to select campgains (would be buggy if hovering switches the campgain description and the mouse is randomly resting ontop of a campgain).
