### ISSUE TITLE
[Feature Request] Lobby starter/Leader having more rights

### ISSUE THREAD

**Issue by wawawawawawawa** [ReactiveDrop/reactivedrop_public_src#609]
Current votekick/voteleader system favors groups, and makes lobby stealing something legal/accepted, since it's the majority rule.
In local lobbies, leader has full right, but having that in dedi servers means potential abuse from players staying in lobbies forever.

To prevent such behavior, while allowing lobby starter to actually choose how/with who he wants to play, why not giving full rights to lobby leader with specific restrictions?

1) Lobby leader have pseudo admin rights for X hours
2) Lobby leader can kick (5min) Y number of times during those X hours
3) Lobby leader can ban (for X hours) Z number of times
4) After X hours, leader either has to change, or leader lose its admin-like privileges'
5) If leader has to change, then you can't be leader more than once (or at least not with admin privileges), to prevent going to alt then back and forth

This would make it so that no singular individual (and no team) can steal/claim a lobby forever, allowing new players to actually have a safe space. It would also prevent things like stalking/harassments, and abusive spectating.

Those could be done as cvar, and actual numbers discussed in forums, but I feel the current system is very flawed, and promotes toxic behavior by making lobby stealing a normal thing.

There are probably other restrictions needed that I can't think about, but this system would make it so that everyone would have the same right to occupy a lobby, without favoring a group over a new player, and would prevent obvious abuse as well.

**Comment by mithrand0** [comment]
First thing that comes into mind, is the following situation:

- Player X joins;
- X wants to play with 'friends' only;
- X kicks/bans everyone during connect.

We had such situation in the past, were a small group of people occupied dedicated servers with this behavior.

**Comment by wawawawawawawa** [comment]
Currently a small group can already occupy a server (even a non empty one) with this behavior, as long as that group is keen on kicking, which favors such behavior.
Allowing smaller groups/single individual to have the same right is normal, as long as it's not abused (by occupying infinitely).
Kicking someone is fine, wanting to play with friends is fine, but the problem is not having the same rights.

If you start a lobby, it's to play as you wish/with who you wish. 
If you go to an occupied lobby, you should abide by the current rules. 
But since lobby starter has no power, what happens is that groups/unwanted players can go to occupied lobbies without a care in the world. This allows stalking, harassments and lobby stealing. 
If such behavior is considered normal, then disregard the request.
If not, then giving temporary power would allow someone to actually have the right to play as he wishes (for a certain time, to prevent abuse), without requiring him to have an actual group willing to instantly kick.

**Comment by BenLubar** [comment]
> First thing that comes into mind, is the following situation:
> 
>     * Player X joins;
> 
>     * X wants to play with 'friends' only;
> 
>     * X kicks/bans everyone during connect.
> 
> 
> We had such situation in the past, were a small group of people occupied dedicated servers with this behavior.

If people don't want to play with each other, I don't see any difference in outcome between which party kicks the other.

**Comment by jhh8** [comment]
i feel like leader abusing will become a bigger issue than lobby stealing after this, which doesnt happen to often anyway. maybe making that leader counts for half of votes, at max

**Comment by wawawawawawawa** [comment]
Don't forget this would also lessen stalking, harrassing (which I'm sure you're aware happened often to me) and spectating abuse.

As for the abuse, both common abuse would be taken care of : 
- staying infinitely in lobby -> leader only for X hours
- trolling to stay alone and kick all -> leader only have Y kicks and Z bans

What other kind of abuse are you talking about? Or do you feel these 2 sentences are the abuse in itself?

> If you start a lobby, it's to play as you wish/with who you wish. 
If you go to an occupied lobby, you should abide by the current rules.

**Comment by jhh8** [comment]
imagine the leader is a person who hates you, you would get kicked all the time even if others want you to stay

**Comment by wawawawawawawa** [comment]
And wouldn't that be fine? I mean, why would you even join a game where the leader is someone who hates you? Isn't it rude in the first place?
Especially considering he can do it only for a certain time, do you HAVE to join him?
But yeah, you're describing stalking/harassing in that case, which shouldn't even happen, no?

**Comment by jhh8** [comment]
if theres 5 friends and one hater in a lobby you want to join to do some chilling relaxing but the bad guy is the leader and you cant play

**Comment by wawawawawawawa** [comment]
then that guy can go to an empty lobby and ask his 5 friends to join him instead? If not, you mean that when you go to an empty lobby, you shouldn't be able to play with who you wish?

**Comment by jhh8** [comment]
its definitely a plus to kick a shit who comes in and says RNG4 to let him know that not gonna happen but thats the only plus really

advanced lobby stealing tactics can be born with a CLSM (coordinated lobby stealing maneuver) where players coordinate to vote someone else leader in a nanosecond for him not be able to react in time, even without a CLSM what does leader have to do to prevent lobby stealing, paranoically kick everyone who they think will not want to play the current map/challenge? more hate will be born with this

a huge downside which im trying to tell you with this system is that a leader can abuse their power - kick newbies instantly without giving them a chance or kick a player who they dont like but everyone else in the lobby is fine with. now here is where we split in opinions - i think in most cases, including me, people are fine with playing with a person that is abusive in chat, as long as theyre not abusive in the actual game by killing you or something. even if you were kicked for not being liked by the leader then its not necceessaarily true that other players in that lobby will follow you to a new lobby and play with you instead, you will just be left alone kicked in main menu crying

i think democracy already works good from what ive experienced

**Comment by ax-now** [comment]
welcome to democracy bro.

there are servers where the leader/admin is in control of the situation and most of the time it ends up in abusive kicks because the leader does not like this person or this one. 

that the leader is a % of the kick vote according to the number of players seems to me a much better idea even if in my opinion this will also encourage abuse. 

I especially have the impression that you have personal problems with certain people in the community and that instead of trying to solve your problems or to ensure that things go smoothly you try to change the rules game to benefit your way of thinking and make your problem solvable using these tools.

in my opinion the idea on paper can be good but knowing this community there will be even more abuse. and there are enough servers to just change over when there's a hostage crisis.

**Comment by wawawawawawawa** [comment]
Kick newbies instantly is something that already happens in asbi eu lobbies regardless, and as you said, the only way to prevent lobby stealing is actually paranoid kick in order to not get overwhelmed by others, which then prevents kick.
This situation incite players to have a group willing to kick instantly.
With my proposal, you don't need to insta kick, because regardless you can kick whenever you want, so it will lessen this issue.

The downside you're talking about is exactly the issue. You start a game, but you can't kick someone that is abusive in chat, or someone stalking you, etc. which promotes toxicity. It feels to me that the abuse you're talking about is that lobby starter shouldn't be able to play as he wants/with who he wants.
If you're left out because you're kicked, maybe there is something you did that made the leader kick you. 
And the same applies to the leader, whether because everyone in lobby decides to leave said lobby to join you, or because you get forced to leave because you can't do anything to prevent someone harassing you.

If democracy > the one who started, then sure, lobby stealing is just not a thing, as it's the expected behavior from the players. 
This means dedicated servers are made mostly for old players with an existing group, and not equally towards new players without a group yet (or with a group that is actually nice enough to not want to votekick).

**Comment by jhh8** [comment]
there will be 10 times more kicks than before, community splitting, more hate

people who just want to play the game and dont care about what happens in chat will now just have a random chance of getting kicked from someone getting too sensititve

**Comment by wawawawawawawa** [comment]
so you mean people will try to behave better in order to not get kicked instead of allowing themselves anything since no repercussions?
also to prevent abuse, there is a restriction on number of kick/ban.

**Comment by jhh8** [comment]
people will not start behaving better thats for sure, thats not how people work

kick/ban restriction will make it even worse for your purpose in particular of preventing lobby stealing and will affect leader-power-abusing to kick single individuals less than lobby stealing

if you dont care about what happens in chat then you stay in the lobby and play the game, which is what i do and i recommend you do

if you dont want toxicity in chat then mute people and just keep playing

**Comment by ax-now** [comment]
Welcome on the Internet,

it happens that people are unbearable, it also happens that you are unbearable for other people and most of the people are correct but when they are not you could mute them and report them to an admin, why would you want to destroy democracy ?
there are two different ways to be a toxic player, the first is players who have an unpleasant verbal and written behavior, it's quite easy to solve as a problem with a simple mute.

the second category is players who are toxic by their action and their gameplay (tk, trolling, no respect for the meta in the tryhard challenge, rushing, etc.). this one is not more difficult to solve there are two options, kick the toxic guy and I think it won't be so hard to do it if everyone agrees with you and it's not personal or you could always send a demo of your games to an admin so that he can see the problem.

everyone should be free to join any server they want.

**Comment by wawawawawawawa** [comment]
it would prevent lobby stealing and prevent stalking, depending on the number of kicks/bans.
if you don't care about toxicity, and prefers to favor it then yes, the current system is indeed best.
if you think toxicity shouldn't be accepted, then you can do something about it, unlike now.
if the goal is to create a toxic atmosphere, then sure, nothing needs to change.

> it happens that people are unbearable, it also happens that you are unbearable for other people and most of the people are correct

That's why it should be fair, if I'm unbearable, I shouldn't join those players, and they shouldn't join me. 
If they decide to still join me, especially when there are empty lobbies, aren't they in the wrong? toxic players should prevail instead?

**Comment by ax-now** [comment]
1. You are not the center of the world and may be that toxic players who join your lobby actually want to play with their friends who are also in your lobby.
2. if you really think that your idea and the right solution you really have to question yourself, it took 2 minutes for jh and me to realize that it was a bad idea.
3. it starts to look like a discussion between my drunk friend and me trying to dissuade him from driving, so i'm going to stop here, have fun.

**Comment by wawawawawawawa** [comment]
If your friends stay in the lobby even though you were being kicked instead of joining you, it might just means they don't think it's toxic, and there are good reasons you were being kicked.
Making it as if the abuser is the abused is fallacy. If you join someone on purpose to make him leave, and that is the correct behavior, then sure, toxicity doesn't exist.

**Comment by snoopchallenge** [comment]
i think this should remain as it is

**Comment by krtek2k** [comment]
> If people don't want to play with each other, I don't see any difference in outcome between which party kicks the other.

if you are the leader, you obviously are setting the rules of the game and kinda "lead" the lobby; and probably were first on the server in the first place. How you can say that there is no difference. Makes no sense and clearly not using a common sense.

I seen asbi players kicking all the players from current lobby, because the server had better ping and they wanted to move as a group to another server.

I seen players getting stalked across the dedicated server and kicking them out of there repeatedly. Just for fun.

> if you dont care about what happens in chat then you stay in the lobby and play the game, which is what i do and i recommend you do

again, you get kicked out of your own lobby, these arguments are just passive aggresive and it makes no sense.

> everyone should be free to join any server they want.

just facepalm, maybe about what is this topic in the first place? Monkeys eating bananas?


Obviously nothing will ever change in this old boring shitgame and it is dead already anyways. Move on.

**Comment by mithrand0** [comment]
The problem I have with this suggestion, is that 'having more rights', is a way to fight a symptom: toxicity of some players.

I already experimented way back in the past, with having more rights. The issue was, there were players kicking everyone out of the game, because they "didn't want to play with them". When we allow this on official dedicated servers, those servers will become friends only effectively. People will just start kicking out everyone they don't like, regardless the reason, or not. This is the main reason I am against changing the voting system. 

The issue to solve the toxicity in the first place, is player reports and moderation. You can compare it to real life. Leader voting rights is comparable to 'self justice', while reports and moderation can be compared to 'police reports and judges'. If we promote self justice, there is a chance we might not only violate the Steam conduct ourselves, but we'd also make things worse by supporting those 'toxic players' who kick/ban everyone they don't like. Good luck then finding a game as new player.

**Comment by krtek2k** [comment]
Even tho I can agree with that, it took years to take down individual like Nyu and made me quit playing the game completely for almost 2years, and take down cheater; like Sun, couple of months even with my demo and trying to contact every owner of the servers avaiable at the moment.

And I remember people having fun about Nyu bullying in the game and refuse to votekick with the last vote.

That is unacceptable as well.

**Comment by krtek2k** [comment]
And you might not see it yet now, but with bigger playerbase, the problems would rise exponentially; as I understand, now the biggest issue about this topic, is a fear about losing even the rest of the playerbase.

Which wont happen, these people are addicted and it is the only thing they are good at in their lifes. So no matter what you do, you cannot basically do anything worse about the playerbase situation that already is.

Face the facts.
