### ISSUE TITLE
Reduction

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_public_src#618]
Back in 2016 we got permission to add the Reduction campaign to AS:RD. This is the implementation meta-issue. Better late than never.

**Comment by BenLubar** [comment]
The reason the video looks so bad is that in Alien Swarm (2010), disabling an asw_broadcast_camera would send the game into infinite recursion and then crash. So the mapper used an in-world camera monitor like what Half-Life 2 uses for the video screens in the first chapter, which are not intended to be used full-screen.

**Comment by jhh8** [comment]
here are the changes for upcoming beta 

https://pastebin.com/Sh8mGZYT

**Comment by jhh8** [comment]
things left to do besides testing and map changes:

- [ ] Cake coordinates
- [ ] Loading screens
- [ ] Figure out better names for missions (suggestions are welcome)
- [ ] Localize rest of strings (instructor hints/voice acting cc, campaign and new mission names)

Ben wants to have voice acting instead of instructor hints, so if we do that then additional task:
- [ ] Replace instructor hints with voice acting

**Comment by jhh8** [comment]
hm my map6 log is clean unless those errors happen only on final compile

**Comment by BenLubar** [comment]
figured out corrupt props, currently making a beta build for it

**Comment by BenLubar** [comment]
Did a playthrough and recorded my live feedback:

https://www.youtube.com/playlist?list=PLEvDAIFuHC348zn46w-4pEGSGj62GAc8b

**Comment by jhh8** [comment]
gave my comments
