### ISSUE TITLE
[bug] workshop map loading bug caused by switching steam account s

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#642]
Please turn audio on. Volume might be low.

https://youtu.be/oMt4g8nJcV0?si=G1I8HaborI7yRxy2

**Comment by BenLubar** [comment]
The list of disabled workshop addons is a text file, and it doesn't have a steam ID in its filename like some of the other files we upload to Steam Cloud.

Not seeing a campaign in the mission chooser when its addon is disabled is expected behavior - disabled addons only show up in the addon list and are not loaded for any other purpose. My guess for why it shows up once is that it's loading the disabled workshop addon list before retrieving it from the Steam Cloud?
